In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("june2026.csv")
df.head()

,subject,9,8,7,6,5,4,3,2,1,U
0,ARABIC (FIRST LANGUAGE),18.7,38.7,56.8,71.6,82.1,91.1,96.6,98.5,99.6,100.0
1,ACCOUNTING,7.5,18.3,32.0,43.2,54.4,63.1,77.3,88.8,97.0,100.0
2,BANGLA,45.9,70.5,82.4,90.9,95.2,97.2,98.7,99.4,99.8,100.0
3,BIOLOGY,20.8,37.3,52.5,64.7,74.3,82.5,88.6,92.8,96.0,100.0
4,BANGLADESH STUDIES,1.6,15.3,29.8,55.6,72.6,86.3,96.8,99.2,99.2,100.0

In [6]:
df.set_index('subject', inplace=True)

In [17]:
df.dropna(inplace=True)

In [18]:
df.index

Index(['ARABIC (FIRST LANGUAGE)', 'ACCOUNTING', 'BANGLA', 'BIOLOGY',
       'BANGLADESH STUDIES', 'BUSINESS', 'CHEMISTRY', 'COMMERCE', 'CHINESE',
       'COMPUTER SCIENCE', 'ENGLISH LANGUAGE A', 'ENGLISH LANGUAGE B',
       'ECONOMICS', 'ENGLISH LITERATURE', 'ART & DESIGN:FINE ART', 'FRENCH',
       'ART & DESIGN:GRAPH.COMM.', 'GEOGRAPHY', 'GREEK (FIRST LANGUAGE)',
       'GLOBAL CITIZENSHIP', 'GERMAN', 'HUMAN BIOLOGY', 'HISTORY',
       'ISLAMIC STUDIES', 'ICT', 'MATHEMATICS A', 'PAKISTAN STUDIES',
       'PHYSICS', 'ART & DESIGN:PHOTOGRAPHY', 'RELIGIOUS STUDIES', 'SINHALA',
       'SPANISH', 'SCIENCE (SINGLE AWARD)', 'SWAHILI', 'TAMIL',
       'ART & DESIGN:3D DESIGN', 'ART & DESIGN:TEXTILE DES.'],
      dtype='object', name='subject')

In [24]:
to_drop = ['ARABIC (FIRST LANGUAGE)','BANGLA', 'BANGLADESH STUDIES', 'ART & DESIGN:GRAPH.COMM.', 'GREEK (FIRST LANGUAGE)',
          'ISLAMIC STUDIES', 'ART & DESIGN:PHOTOGRAPHY', 'PAKISTAN STUDIES', 'SINHALA', 'SWAHILI', 'TAMIL']
df.drop(to_drop, inplace = True)
df

,9,8,7,6,5,4,3,2,1,U
subject,,,,,,,,,,
ACCOUNTING,7.5,18.3,32.0,43.2,54.4,63.1,77.3,88.8,97.0,100.0
BIOLOGY,20.8,37.3,52.5,64.7,74.3,82.5,88.6,92.8,96.0,100.0
BUSINESS,5.2,15.5,29.2,47.2,63.1,76.1,84.9,90.9,94.8,100.0
CHEMISTRY,22.8,43.1,59.5,69.2,76.5,82.9,88.4,92.2,95.8,100.0
COMMERCE,11.1,20.0,29.4,39.9,51.0,58.7,73.0,82.7,88.9,100.0
CHINESE,45.8,70.4,77.6,81.3,84.1,86.4,91.5,94.8,98.5,100.0
COMPUTER SCIENCE,9.5,20.3,30.1,42.9,56.3,68.3,85.0,94.8,99.3,100.0
ENGLISH LANGUAGE A,11.5,24.4,42.1,64.7,81.2,90.2,96.5,99.1,99.7,100.0
ENGLISH LANGUAGE B,12.6,26.1,43.8,55.3,66.0,75.3,94.5,99.1,99.8,100.0
ECONOMICS,12.2,25.1,40.5,53.3,63.1,71.2,80.6,87.1,91.9,100.0
ENGLISH LITERATURE,20.8,35.2,51.9,75.6,89.6,96.2,98.9,99.7,99.9,100.0
ART & DESIGN:FINE ART,4.8,11.4,21.7,39.2,56.8,73.2,87.6,96.0,99.3,100.0
FRENCH,28.6,49.3,65.4,76.3,84.8,89.7,95.6,98.6,99.8,100.0
GEOGRAPHY,14.8,33.0,50.9,67.1,79.6,87.7,93.2,96.9,98.8,100.0
GLOBAL CITIZENSHIP,12.8,26.0,41.0,55.6,68.6,77.2,88.7,94.9,98.5,100.0
GERMAN,26.1,51.5,68.9,83.8,92.0,96.0,98.0,98.7,99.1,100.0
HUMAN BIOLOGY,14.1,34.0,51.1,67.0,77.4,84.3,90.9,95.0,97.9,100.0
HISTORY,21.3,39.6,56.5,69.9,79.7,86.9,94.0,97.9,99.5,100.0
ICT,4.1,12.2,22.7,38.2,53.5,68.2,81.9,91.1,96.7,100.0
MATHEMATICS A,21.9,39.9,56.1,68.4,80.4,89.0,94.0,95.8,96.6,100.0
PHYSICS,22.9,43.2,60.1,70.3,78.3,84.4,89.6,93.3,96.0,100.0
RELIGIOUS STUDIES,21.1,39.5,55.7,67.5,76.5,82.5,87.4,90.4,93.1,100.0
SPANISH,44.1,61.9,76.1,83.9,89.8,94.5,97.2,98.7,99.7,100.0
SCIENCE (SINGLE AWARD),5.0,12.4,19.7,29.0,36.6,46.8,58.6,72.7,86.3,100.0
ART & DESIGN:3D DESIGN,10.3,23.0,25.3,37.9,56.3,81.6,97.7,100.0,100.0,100.0
ART & DESIGN:TEXTILE DES.,13.3,25.5,35.7,56.1,75.5,80.6,93.9,100.0,100.0,100.0

In [35]:
new_data = df.copy()

In [39]:
for i in reversed(range(1, new_data.shape[1])):
    new_data.iloc[:,i] -= new_data.iloc[:,i-1]

In [40]:
new_data

,9,8,7,6,5,4,3,2,1,U
subject,,,,,,,,,,
ACCOUNTING,7.5,10.8,13.7,11.2,11.2,8.7,14.2,11.5,8.2,3.0
BIOLOGY,20.8,16.5,15.2,12.2,9.6,8.2,6.1,4.2,3.2,4.0
BUSINESS,5.2,10.3,13.7,18.0,15.9,13.0,8.8,6.0,3.9,5.2
CHEMISTRY,22.8,20.3,16.4,9.7,7.3,6.4,5.5,3.8,3.6,4.2
COMMERCE,11.1,8.9,9.4,10.5,11.1,7.7,14.3,9.7,6.2,11.1
CHINESE,45.8,24.6,7.2,3.7,2.8,2.3,5.1,3.3,3.7,1.5
COMPUTER SCIENCE,9.5,10.8,9.8,12.8,13.4,12.0,16.7,9.8,4.5,0.7
ENGLISH LANGUAGE A,11.5,12.9,17.7,22.6,16.5,9.0,6.3,2.6,0.6,0.3
ENGLISH LANGUAGE B,12.6,13.5,17.7,11.5,10.7,9.3,19.2,4.6,0.7,0.2
ECONOMICS,12.2,12.9,15.4,12.8,9.8,8.1,9.4,6.5,4.8,8.1
ENGLISH LITERATURE,20.8,14.4,16.7,23.7,14.0,6.6,2.7,0.8,0.2,0.1
ART & DESIGN:FINE ART,4.8,6.6,10.3,17.5,17.6,16.4,14.4,8.4,3.3,0.7
FRENCH,28.6,20.7,16.1,10.9,8.5,4.9,5.9,3.0,1.2,0.2
GEOGRAPHY,14.8,18.2,17.9,16.2,12.5,8.1,5.5,3.7,1.9,1.2
GLOBAL CITIZENSHIP,12.8,13.2,15.0,14.6,13.0,8.6,11.5,6.2,3.6,1.5
GERMAN,26.1,25.4,17.4,14.9,8.2,4.0,2.0,0.7,0.4,0.9
HUMAN BIOLOGY,14.1,19.9,17.1,15.9,10.4,6.9,6.6,4.1,2.9,2.1
HISTORY,21.3,18.3,16.9,13.4,9.8,7.2,7.1,3.9,1.6,0.5
ICT,4.1,8.1,10.5,15.5,15.3,14.7,13.7,9.2,5.6,3.3
MATHEMATICS A,21.9,18.0,16.2,12.3,12.0,8.6,5.0,1.8,0.8,3.4
PHYSICS,22.9,20.3,16.9,10.2,8.0,6.1,5.2,3.7,2.7,4.0
RELIGIOUS STUDIES,21.1,18.4,16.2,11.8,9.0,6.0,4.9,3.0,2.7,6.9
SPANISH,44.1,17.8,14.2,7.8,5.9,4.7,2.7,1.5,1.0,0.3
SCIENCE (SINGLE AWARD),5.0,7.4,7.3,9.3,7.6,10.2,11.8,14.1,13.6,13.7
ART & DESIGN:3D DESIGN,10.3,12.7,2.3,12.6,18.4,25.3,16.1,2.3,0.0,0.0
ART & DESIGN:TEXTILE DES.,13.3,12.2,10.2,20.4,19.4,5.1,13.3,6.1,0.0,0.0

In [43]:
new_data.to_csv("june2026new.csv")

In [44]:
test = pd.read_csv('june2026new.csv')
test.head()

      subject     9     8     7     6     5     4     3     2    1     U
0  ACCOUNTING   7.5  10.8  13.7  11.2  11.2   8.7  14.2  11.5  8.2   3.0
1     BIOLOGY  20.8  16.5  15.2  12.2   9.6   8.2   6.1   4.2  3.2   4.0
2    BUSINESS   5.2  10.3  13.7  18.0  15.9  13.0   8.8   6.0  3.9   5.2
3   CHEMISTRY  22.8  20.3  16.4   9.7   7.3   6.4   5.5   3.8  3.6   4.2
4    COMMERCE  11.1   8.9   9.4  10.5  11.1   7.7  14.3   9.7  6.2  11.1